🐠 Added UpdateUserEmail patch
passageidentity/passage-go pull request #5
Opened 2021-09-27 14:46 UTC by dylanbrookes

user.go -> added UpdateUserEmail function

user_test.go -> added TestUpdateUserEmail

<sup> Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>

2021-09-28 02:49 UTC, apobletts requested changes

2021-09-28 02:49 UTC, apobletts commented on user.go
> +		SetBody(fmt.Sprintf(`{"email": %v}`, email)).
I believe the correct way to do this is using a quick struct

type updateBody struct {
      Email string `json:"email"`
}
...
then use that struct in the SetBody

2021-10-18 17:40 UTC, apobletts commented
@dylanbrookes sorry for the delay on this, but I think we agreed to change all these to updateUser to be able to update any fields in the future.

2021-10-28 17:10 UTC, calhorn95 commented on user.go
> +	Phone         string    `json:"phone"`
*****phone_number

2021-11-02 15:15 UTC, dylanbrookes commented on user.go
> +	Phone         string    `json:"phone"`
Resolving this conversation; we've moved to `phone`

2021-11-02 18:00 UTC, calhorn95 approved these changes

2021-11-02 18:29 UTC, merged