add create magic-link functionality
passageidentity/passage-go pull request #8
Opened 2022-02-25 21:49 UTC by calhorn95

SHOULD NOT BE MERGED UNTIL SMART LINKS MAKE IT TO MAIN

2022-02-25 23:00 UTC, dylanbrookes requested changes

2022-02-25 23:00 UTC, dylanbrookes commented on app_test.go
> +func TestCreateMagiLinke(t *testing.T) {
typo `TestCreateMagiLinke` --change to --> `TestCreateMagicLink`

2022-03-03 18:51 UTC, apobletts approved these changes

2022-03-03 18:52 UTC, apobletts approved these changes

2022-03-03 21:42 UTC, merged